# Generated by Django 6.0 on 2026-01-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('afiliado', models.IntegerField(verbose_name='Afiliado')),
                ('dni', models.IntegerField(null=True, verbose_name='DNI')),
                ('seccion', models.CharField(max_length=50, verbose_name='Seccion')),
                ('turno', models.CharField(max_length=20, verbose_name='Turno')),
                ('reparticion', models.CharField(max_length=50, verbose_name='Reparticion')),
                ('horasquetrabaja', models.IntegerField(verbose_name='Horas que trabaja')),
                ('horadeingreso', models.TimeField(null=True, verbose_name='Horario de ingreso')),
                ('horadeegreso', models.TimeField(null=True, verbose_name='Horario de salida')),
            ],
        ),
    ]
