# Generated by Django 6.0 on 2026-01-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0002_empleado_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='cositas',
            fields=[
                ('id_cosita', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cosita', models.CharField(max_length=100, verbose_name='Nombre de la cosita')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion de la cosita')),
            ],
        ),
    ]
