# Generated by Django 6.0 on 2026-01-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0003_cositas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cositas',
        ),
    ]
